version: '3.3'
services:
  react-builder:
    container_name: react-builder
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./:/app

  nginx:
    container_name: hanseifood_ws
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./certbot/www/:/var/www/certbot
      # - ./certbot/conf/:/etc/letsencrypt
    restart: unless-stopped
    ports:
      # - 443:443
      - 80:80
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    depends_on:
      - react-builder

  # certbot:
  #   container_name: certbot
  #   image: certbot/certbot:latest
  #   restart: unless-stopped
  #   volumes:
  #     - ./certbot/www/:/var/www/certbot
  #     - ./certbot/conf/:/etc/letsencrypt
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  #   depends_on:
  #     - nginx
  #     - react-builder
