version: '3.3'
services:
  react-builder:
    container_name: react-builder
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./:/app

  nginx:
    container_name: cba_ws
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    restart: always
    ports:
      - 443:443
      - 80:80
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    depends_on:
      - react-builder

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: >
      certonly --webroot --webroot-path=/var/www/certbot --email jipkim2@gmail.com --agree-tos --no-eff-email --non-interactive --keep-until-expiring -d recba.me -d www.recba.me

  # certbot:
  #   container_name: certbot
  #   image: certbot/certbot:latest
  #   restart: unless-stopped
  #   volumes:
  #     - ./certbot/www/:/var/www/certbot
  #     - ./certbot/conf/:/etc/letsencrypt
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

